Repository AY1920S2-CS2113T-T12-3/tp, pull requests merged in 2020-04, with the labels that each got.

#142 Handle exceptions related to Scheduling tasks
  .gitignore
  src/main/java/task/SchedulableTask.java
  src/main/java/task/TaskScheduler.java
Labels: severity.Low, type.Bug

#171 Update message when search command doesn't find any matched tasks.
  src/main/java/ui/Constants.java
  text-ui-test/EXPECTED.TXT
Labels: type.Bug

#172 Update changes
  docs/UserGuide.md
  src/main/java/calendarview/CalendarView.java
  src/main/java/calendarview/TaskComparator.java
  src/main/java/command/CalenderCommand.java
  src/main/java/parser/Parser.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/task/Deadline.java
  src/main/java/task/Event.java
  src/main/java/ui/Constants.java
  src/main/java/ui/Ui.java
  text-ui-test/EXPECTED.TXT
Labels: type.Task

#173 Update capitalisation
  docs/UserGuide.md
Labels: severity.Low

#174 Fix issues reported during PE-Dry Run
  src/main/java/command/AddDeadlineCommand.java
  src/main/java/command/AddEventCommand.java
  src/main/java/exception/command/DeadlineCompletionStatusNotABooleanException.java
  src/main/java/exception/command/DeadlineCreationDueTimeMissingException.java
  src/main/java/exception/command/DeadlineDetailsNotProvidedException.java
  src/main/java/exception/command/DescriptionContainsInvalidCharacterException.java
  src/main/java/exception/command/EventCreationEndTimeMissingException.java
  src/main/java/exception/command/EventCreationStartTimeMissingException.java
  src/main/java/exception/command/TaskCreationDateMissingException.java
  src/main/java/exception/command/TaskCreationDescriptionMissingException.java
  src/main/java/exception/command/TaskCreationPriorityMissingException.java
  src/main/java/task/Deadline.java
  src/main/java/task/TaskList.java
  src/main/java/ui/Constants.java
Labels: type.Bug

#175 Update gradle checks and fix major Notes bugs
  src/main/java/exception/NotesCommandException.java
  src/main/java/exception/NotesInvalidAddMessageException.java
  src/main/java/notes/ModulesList.java
  src/main/java/notes/Notes.java
  src/main/java/notes/NotesInvoker.java
  src/main/java/notes/modules/ModuleManager.java
  src/main/java/notes/modules/parser/Parser.java
Labels: severity.Low

#178 Add more JUnit tests
  src/main/java/exception/command/SchedulableTaskDaysLeftNotIntegerException.java
  src/main/java/exception/command/SchedulableTaskDaysLeftNotPositiveException.java
  src/main/java/exception/command/SchedulableTaskDaysToFinishMoreThanDaysLeftException.java
  src/main/java/exception/command/SchedulableTaskDaysToFinishNotIntegerException.java
  src/main/java/exception/command/SchedulableTaskDaysToFinishNotPositiveException.java
  src/main/java/exception/command/SchedulableTaskEmptyDescriptionException.java
  src/main/java/exception/command/SchedulableTaskFormatNotFollowedException.java
  src/main/java/task/Event.java
  src/main/java/task/SchedulableTask.java
  src/main/java/task/TaskScheduler.java
  src/test/java/task/DeadlineTest.java
  src/test/java/task/SchedulableTaskTest.java
Labels: type.Task

#179 Update PPP
  docs/team/ganapathysanathbalaji.md
Labels: type.Task

#180 Update PPP formatting
  docs/team/ganapathysanathbalaji.md
Labels: type.Task

#181 Change spacing in PPP
  docs/team/ganapathysanathbalaji.md
Labels: type.Task

#182 Rectify issues with PPP
  docs/team/ganapathysanathbalaji.md
Labels: type.Task

#183 Update formatting of PPP
  docs/team/ganapathysanathbalaji.md
Labels: type.Task

#188 Update changes based on Nizar's PR
  docs/DeveloperGuide.md
  docs/images/isAvailStudyArea.png
  docs/images/user_sL_interaction.png
  src/main/java/calendarview/CalendarView.java
  src/main/java/command/CalendarCommand.java
  src/main/java/parser/Parser.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/task/Deadline.java
  src/main/java/task/Event.java
  src/main/java/ui/Constants.java
  src/test/java/task/DeadlineTest.java
  src/test/java/task/EventTest.java
Labels: type.Task

#193 Add author tags
  src/main/java/task/Deadline.java
  src/main/java/task/TaskList.java
  src/main/java/ui/Ui.java
Labels: type.Task

#194 Change file name of images to make them Reposense compatible
  docs/DeveloperGuide.md
  docs/images/ScheduleOverall.png
  docs/images/ScheduleSub1.png
  docs/images/ScheduleSub2.png
  docs/images/ScheduleSub3.png
  docs/images/TaskComponent.jpg
  docs/images/TaskComponentUML.png
  docs/images/sLinteraction.png
  docs/images/usersLinteraction.png
  docs/team/ganapathysanathbalaji.md
Labels: type.Task

#195 Change UML code file names to be Reposense compatible
  docs/UMLCode/AddScheduledTasksToList.txt
  docs/UMLCode/Architecture.txt
  docs/UMLCode/CheckAndScheduleTasks.txt
  docs/UMLCode/GetSchedulabeTaskInformation.txt
  docs/UMLCode/ScheduleOverall.txt
  docs/UMLCode/TaskComponent.txt
  docs/UMLCode/sLinteraction.txt
  docs/UMLCode/studyAreaObjectDiagram.txt
  docs/UMLCode/usersLinteraction.txt
Labels: type.Task

#196 Update Changes
  src/main/java/calendarview/CalendarView.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/studyarea/StudyArea.java
  src/main/java/studyarea/StudyAreaList.java
  src/main/java/ui/Constants.java
  src/test/java/calendarview/CalendarViewTest.java
  src/test/java/studyarea/StudyAreaListTest.java
  src/test/java/studyarea/StudyAreaTest.java
Labels: type.Task

#198 Add more JUnit tests
  src/main/java/task/Deadline.java
  src/main/java/task/Event.java
  src/main/java/task/SchedulableTask.java
  src/main/java/task/SchedulableTaskComparator.java
  src/main/java/task/TaskList.java
  src/main/java/task/TaskScheduler.java
  src/main/java/task/TaskType.java
  src/test/java/task/TaskListTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Task

#199 Notes finalized
  src/main/java/notes/ModulesList.java
  src/main/java/notes/Notes.java
  src/main/java/notes/NotesInvoker.java
  src/main/java/notes/modules/ModuleManager.java
  src/main/java/notes/modules/command/CommandStack.java
  src/main/java/notes/modules/command/ListCommand.java
  src/main/java/notes/modules/parser/Parser.java
  src/main/java/ui/Constants.java
Labels: severity.Medium

#200 Add minor improvements to notes feature and clear command
  docs/UserGuide.md
  src/main/java/notes/ModulesList.java
  src/main/java/notes/NotesInvoker.java
  src/main/java/task/TaskList.java
  src/main/java/ui/Constants.java
  src/test/java/task/TaskListTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Task

#201 Update regarding Github pages
  docs/AboutUs.md
  docs/README.md
  docs/UserGuide.md
  docs/images/Sanath.png
  docs/team/hongquan448.md
  docs/team/nizarmohd.md
Labels: type.Task

#203 Update doc links
  docs/AboutUs.md
Labels: type.Task

#206 Notes in UG
  docs/UserGuide.md
  src/main/java/ui/Constants.java
Labels: severity.Medium

#208 Update Changes
  src/main/java/calendarview/TaskComparator.java
  src/main/java/command/CommandWithIndex.java
  src/test/java/studyarea/StudyAreaTest.java
Labels: type.Task

#209 Rectify issue with DG & few minor changes
  docs/DeveloperGuide.md
  docs/images/JUnitConfiguration.PNG
  docs/images/JUnitRunTest.PNG
  docs/images/JUnit_run_test.PNG
  docs/images/elephantIcon.PNG
  docs/images/elephant_icon.PNG
  docs/images/gradleBuild.PNG
  docs/images/gradleRunTest.PNG
  docs/images/gradle_run_test.PNG
  docs/images/studyAreaDet.PNG
  docs/team/nizarmohd.md
  src/main/java/exception/command/SchedulableTaskDaysLeftNotPositiveException.java
  src/main/java/exception/command/SchedulableTaskDaysToFinishNotPositiveException.java
  src/main/java/notes/ModulesList.java
  src/main/java/ui/Constants.java
  src/test/java/task/SchedulableTaskTest.java
Labels: type.Task

#212 Update DG
  docs/DeveloperGuide.md
Labels: type.Task

#214 Refactor code and edit DG
  .gitignore
  docs/DeveloperGuide.md
  docs/team/ganapathysanathbalaji.md
  src/main/java/command/AddDeadlineCommand.java
  src/main/java/command/AddEventCommand.java
  src/main/java/exception/command/DeadlineCompletionStatusNotABooleanException.java
  src/main/java/task/Deadline.java
  src/main/java/task/Event.java
  src/main/java/task/TaskList.java
  src/main/java/ui/Constants.java
  src/test/java/task/TaskListTest.java
Labels: type.Task

#215 Update DG
  docs/DeveloperGuide.md
Labels: type.Task

#216 Add ui.png
  docs/README.md
  docs/images/ui.png
  src/main/java/seedu/duke/Duke.java
Labels: type.Task

#218 Refactor code
  src/main/java/command/AddDeadlineCommand.java
  src/main/java/command/AddEventCommand.java
  src/main/java/command/CalendarCommand.java
  src/main/java/command/CommandWithIndex.java
  src/main/java/command/CreateScheduleCommand.java
  src/main/java/command/SearchCommand.java
  src/main/java/exception/NotesCommandException.java
  src/main/java/exception/NotesInvalidAddMessageException.java
  src/main/java/exception/command/DeadlineCreationDueTimeMissingException.java
  src/main/java/exception/command/DeadlineCreationFormatNotFollowedException.java
  src/main/java/exception/command/DeadlineDetailsNotProvidedException.java
  src/main/java/exception/command/DescriptionContainsInvalidCharacterException.java
  src/main/java/exception/command/EmptyDescriptionException.java
  src/main/java/exception/command/EventCreationEndTimeMissingException.java
  src/main/java/exception/command/EventCreationFormatNotFollowedException.java
  src/main/java/exception/command/EventCreationStartTimeMissingException.java
  src/main/java/exception/command/EventDetailsNotProvidedException.java
  src/main/java/exception/command/EventStartTimeAfterEndTimeException.java
  src/main/java/exception/command/IndexNotIntegerException.java
  src/main/java/exception/command/InvalidDateException.java
  src/main/java/exception/command/InvalidDueTimeException.java
  src/main/java/exception/command/InvalidEndTimeException.java
  src/main/java/exception/command/InvalidHelpCommandException.java
  src/main/java/exception/command/InvalidStartTimeException.java
  src/main/java/exception/command/MisuseOfClearCommandException.java
  src/main/java/exception/command/MisuseOfCountdownCommandException.java
  src/main/java/exception/command/MisuseOfPriorityCommandException.java
  src/main/java/exception/command/MisuseOfScheduleCommandException.java
  src/main/java/exception/command/MisuseOfSetDoneWithEvent.java
  src/main/java/exception/command/MisuseOfViewCommandException.java
  src/main/java/exception/command/NumberOfTasksToBeScheduledNotAnIntegerException.java
  src/main/java/exception/command/NumberOfTasksToBeScheduledNotPositiveException.java
  src/main/java/exception/command/SchedulableTaskDaysLeftNotIntegerException.java
  src/main/java/exception/command/SchedulableTaskDaysLeftNotPositiveException.java
  src/main/java/exception/command/SchedulableTaskDaysToFinishMoreThanDaysLeftException.java
  src/main/java/exception/command/SchedulableTaskDaysToFinishNotIntegerException.java
  src/main/java/exception/command/SchedulableTaskDaysToFinishNotPositiveException.java
  src/main/java/exception/command/SchedulableTaskEmptyDescriptionException.java
  src/main/java/exception/command/SchedulableTaskFormatNotFollowedException.java
  src/main/java/exception/command/SearchKeywordEmptyException.java
  src/main/java/exception/command/SearchMissingTermsException.java
  src/main/java/exception/command/TaskCreationDateMissingException.java
  src/main/java/exception/command/TaskCreationDescriptionMissingException.java
  src/main/java/exception/command/TaskCreationPriorityMissingException.java
  src/main/java/exception/command/TaskDateBeforeCurrentDateException.java
  src/main/java/exception/command/TaskPriorityNotIntegerException.java
  src/main/java/parser/Parser.java
Labels: type.Task

#219 Update UG and refactor code
  docs/UserGuide.md
  src/main/java/command/CommandWithIndex.java
  src/main/java/exception/CustomException.java
  src/main/java/exception/NotesCommandException.java
  src/main/java/exception/NotesInvalidAddMessageException.java
  src/main/java/exception/command/DeadlineCompletionStatusNotABooleanException.java
  src/main/java/exception/command/DeadlineCreationDueTimeMissingException.java
  src/main/java/exception/command/DeadlineCreationFormatNotFollowedException.java
  src/main/java/exception/command/DeadlineDetailsNotProvidedException.java
  src/main/java/exception/command/DescriptionContainsInvalidCharacterException.java
  src/main/java/exception/command/EmptyDescriptionException.java
  src/main/java/exception/command/EventCreationEndTimeMissingException.java
  src/main/java/exception/command/EventCreationFormatNotFollowedException.java
  src/main/java/exception/command/EventCreationStartTimeMissingException.java
  src/main/java/exception/command/EventDetailsNotProvidedException.java
  src/main/java/exception/command/EventStartTimeAfterEndTimeException.java
  src/main/java/exception/command/IllegalDoneCommandException.java
  src/main/java/exception/command/IndexNotIntegerException.java
  src/main/java/exception/command/InvalidDateException.java
  src/main/java/exception/command/InvalidDueTimeException.java
  src/main/java/exception/command/InvalidEndTimeException.java
  src/main/java/exception/command/InvalidHelpCommandException.java
  src/main/java/exception/command/InvalidStartTimeException.java
  src/main/java/exception/command/MisuseOfClearCommandException.java
  src/main/java/exception/command/MisuseOfCountdownCommandException.java
  src/main/java/exception/command/MisuseOfPriorityCommandException.java
  src/main/java/exception/command/MisuseOfScheduleCommandException.java
  src/main/java/exception/command/MisuseOfSetDoneWithEvent.java
  src/main/java/exception/command/MisuseOfViewCommandException.java
  src/main/java/exception/command/NumberOfTasksToBeScheduledNotAnIntegerException.java
  src/main/java/exception/command/NumberOfTasksToBeScheduledNotPositiveException.java
  src/main/java/exception/command/SchedulableTaskDaysLeftNotIntegerException.java
  src/main/java/exception/command/SchedulableTaskDaysLeftNotPositiveException.java
  src/main/java/exception/command/SchedulableTaskDaysToFinishMoreThanDaysLeftException.java
  src/main/java/exception/command/SchedulableTaskDaysToFinishNotIntegerException.java
  src/main/java/exception/command/SchedulableTaskDaysToFinishNotPositiveException.java
  src/main/java/exception/command/SchedulableTaskEmptyDescriptionException.java
  src/main/java/exception/command/SchedulableTaskFormatNotFollowedException.java
  src/main/java/exception/command/SearchKeywordEmptyException.java
  src/main/java/exception/command/SearchMissingTermsException.java
  src/main/java/exception/command/TaskCreationDateMissingException.java
  src/main/java/exception/command/TaskCreationDescriptionMissingException.java
  src/main/java/exception/command/TaskCreationPriorityMissingException.java
  src/main/java/exception/command/TaskDateBeforeCurrentDateException.java
  src/main/java/exception/command/TaskPriorityNotIntegerException.java
  src/main/java/resourceloader/BackUpData.java
  src/main/java/task/Task.java
  src/main/java/task/TaskScheduler.java
  src/main/java/ui/Constants.java
  src/main/java/ui/Ui.java
  src/test/java/task/SchedulableTaskTest.java
  src/test/java/task/TaskListTest.java
Labels: type.Task

#221 Update UG
  docs/UserGuide.md
Labels: type.Task

#222 add changes
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Task

#224 Update UG & DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Task

#227 Remove toLowerCase()
  src/main/java/seedu/duke/Duke.java
Labels: type.Task

#231 Add exception to handle F6 key input
  src/main/java/exception/command/IllegalCharactersEnteredException.java
  src/main/java/notes/ModulesList.java
  src/main/java/ui/Ui.java
Labels: type.Bug

#235 Update Author tags
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Task

#236 Update Text-Ui-Test
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Task

#238 Update UG
  docs/UserGuide.md
Labels: type.Task

#239 Rectify formatting issue
  docs/UserGuide.md
Labels: type.Task

#240 Rename .jar file
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Task

#241 Change name of jar file
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Task
