Repository AY1920S2-CS2113T-T12-3/tp, pull requests merged in 2020-03, with the labels that each got.

#13 Branch event
  src/main/java/event/Event.java
  src/main/java/event/EventList.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/ui/Ui.java
Labels: type.Epic, type.Story

#16 Add support to load and save events
  data/EventList.txt
  src/main/java/event/Event.java
  src/main/java/event/EventList.java
  src/main/java/resourceloader/EventLoader.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/ui/Ui.java
Labels: type.Task

#20 Add JUnit Test for Event Class
  src/main/java/event/Event.java
  src/main/java/event/EventList.java
  src/main/java/resourceloader/EventLoader.java
  src/test/java/event/EventTest.java
Labels: type.Task

#24 Pre v1.0
  library/eventList.txt
  src/main/java/command/EventCommand.java
  src/main/java/command/StudyAreaCommand.java
  src/main/java/driver/Driver.java
  src/main/java/resourceloader/Loader.java
  src/main/java/resourceloader/StudyAreaLoader.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/studyarea/StudyArea.java
  src/main/java/studyarea/StudyAreaList.java
  src/main/java/studyarea/Utility.java
  src/main/java/ui/Ui.java
  src/test/java/resourceloader/StudyAreaLoaderTest.java
  src/test/java/studyarea/StudyAreaListTest.java
Labels: severity.Medium, type.Task

#35 Refactor Ui IO stream, Change Logo, Add credits.
  library/eventList.txt
  src/main/java/command/EventCommand.java
  src/main/java/command/StudyAreaCommand.java
  src/main/java/driver/Driver.java
  src/main/java/event/Event.java
  src/main/java/event/EventList.java
  src/main/java/resourceloader/EventLoader.java
  src/main/java/resourceloader/StudyAreaLoader.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/studyarea/IllegalStudyAreaException.java
  src/main/java/studyarea/StudyArea.java
  src/main/java/studyarea/StudyAreaList.java
  src/main/java/ui/Ui.java
Labels: type.Task

#43 Add Deadline to #35
  src/main/java/command/EventCommand.java
  src/main/java/command/StudyAreaCommand.java
  src/main/java/deadline/Deadline.java
  src/main/java/deadline/DeadlineList.java
  src/main/java/driver/Driver.java
  src/main/java/event/Event.java
  src/main/java/event/EventList.java
  src/main/java/resourceloader/EventLoader.java
  src/main/java/resourceloader/StudyAreaLoader.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/studyarea/IllegalStudyAreaException.java
  src/main/java/studyarea/StudyArea.java
  src/main/java/studyarea/StudyAreaList.java
  src/main/java/task/TaskList.java
  src/main/java/ui/Ui.java
Labels: type.Task

#44 Refactored Parser and Command Classes
  src/main/java/command/AddCommand.java
  src/main/java/command/ClearCommand.java
  src/main/java/command/Command.java
  src/main/java/command/CountdownCommand.java
  src/main/java/command/DeleteCommand.java
  src/main/java/command/EventCommand.java
  src/main/java/command/HelpCommand.java
  src/main/java/command/PriorityViewCommand.java
  src/main/java/command/SearchCommand.java
  src/main/java/command/ViewCommand.java
  src/main/java/driver/Driver.java
  src/main/java/event/Event.java
  src/main/java/event/EventList.java
  src/main/java/parser/Parser.java
  src/main/java/resourceloader/EventLoader.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/studyarea/StudyArea.java
  src/main/java/ui/Ui.java
  text-ui-test/ACTUAL.TXT
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
  text-ui-test/library/eventList.txt
  text-ui-test/library/locations.txt
  text-ui-test/runtest.sh
Labels: type.Task

#45 Remove Driver.java
  src/main/java/driver/Driver.java
  src/main/java/seedu/duke/Duke.java
Labels: type.Task

#48 Add JUnit Test for EventList and Parser Class
  src/main/java/command/AddCommand.java
  src/main/java/command/DeleteCommand.java
  src/main/java/event/EventList.java
  src/main/java/parser/Parser.java
  src/test/java/event/EventListTest.java
  src/test/java/parser/ParserTest.java
Labels: type.Task

#57 Remove ACTUAL.TXT
  src/main/java/event/EventList.java
  src/main/java/resourceloader/StudyAreaLoader.java
  text-ui-test/ACTUAL.TXT
  text-ui-test/runtest.sh
Labels: type.Task

#64 Refactor code
  src/main/java/task/TaskList.java
  src/main/java/ui/Ui.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
  text-ui-test/library/taskList.txt
Labels: type.Task

#66 Re-PR for Study Area Update
  library/dictionary.txt
  library/locations.txt
  src/main/java/command/StudyAreaCommand.java
  src/main/java/resourceloader/EventLoader.java
  src/main/java/resourceloader/StudyAreaLoader.java
  src/main/java/studyarea/Dictionary.java
  src/main/java/studyarea/IllegalStudyAreaException.java
  src/main/java/studyarea/StudyArea.java
  src/main/java/studyarea/StudyAreaList.java
  src/main/java/ui/Ui.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/library/dictionary.txt
Labels: type.Task

#67 Study Area Update
  library/dictionary.txt
  library/locations.txt
  src/main/java/command/StudyAreaCommand.java
  src/main/java/command/TaskCommand.java
  src/main/java/resourceloader/BackUpData.java
  src/main/java/resourceloader/StudyAreaLoader.java
  src/main/java/resourceloader/TaskLoader.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/studyarea/Dictionary.java
  src/main/java/studyarea/IllegalStudyAreaException.java
  src/main/java/studyarea/StudyArea.java
  src/main/java/studyarea/StudyAreaList.java
  src/main/java/task/TaskList.java
  src/main/java/ui/Constants.java
  src/main/java/ui/Ui.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
  text-ui-test/library/locations.txt
  text-ui-test/library/taskList.txt
Labels: type.Task

#69 Add assertions, exceptions, and logging to code
  build.gradle
  dukeLogger.log
  src/main/java/command/AddDeadlineCommand.java
  src/main/java/command/AddEventCommand.java
  src/main/java/command/HelpCommand.java
  src/main/java/exception/command/DeadlineCreationFormatNotFollowedException.java
  src/main/java/exception/command/EventCreationFormatNotFollowedException.java
  src/main/java/exception/command/EventStartTimeAfterEndTimeException.java
  src/main/java/exception/command/InvalidDateException.java
  src/main/java/exception/command/InvalidDueTimeException.java
  src/main/java/exception/command/InvalidEndTimeException.java
  src/main/java/exception/command/InvalidHelpCommandException.java
  src/main/java/exception/command/InvalidStartTimeException.java
  src/main/java/exception/command/SearchKeywordEmptyException.java
  src/main/java/exception/command/TaskDateBeforeCurrentDateException.java
  src/main/java/exception/command/TaskPriorityNotIntegerException.java
  src/main/java/resourceloader/TaskLoader.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/studyarea/StudyAreaList.java
  src/main/java/task/Deadline.java
  src/main/java/task/Event.java
  src/main/java/task/TaskList.java
  src/main/java/ui/Ui.java
  src/test/java/studyarea/StudyAreaListTest.java
  src/test/java/task/event/TaskListTest.java
  src/test/java/task/event/TaskTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/dukeLogger.log
  text-ui-test/input.txt
  text-ui-test/library/taskList.txt
Labels: type.Task

#72 Add logging for StudyAreaList and TaskList
  dukeLogger.log
  library/locations.txt
  library/taskList.txt
  src/main/java/command/AddDeadlineCommand.java
  src/main/java/command/AddEventCommand.java
  src/main/java/command/StudyAreaCommand.java
  src/main/java/command/TaskCommand.java
  src/main/java/exception/command/DeadlineCreationFormatNotFollowedException.java
  src/main/java/exception/command/EventCreationFormatNotFollowedException.java
  src/main/java/exception/command/EventStartTimeAfterEndTimeException.java
  src/main/java/exception/command/InvalidEndTimeException.java
  src/main/java/exception/command/TaskPriorityNotIntegerException.java
  src/main/java/resourceloader/BackUpData.java
  src/main/java/resourceloader/StudyAreaLoader.java
  src/main/java/resourceloader/TaskLoader.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/studyarea/Dictionary.java
  src/main/java/studyarea/IllegalStudyAreaException.java
  src/main/java/studyarea/StudyArea.java
  src/main/java/studyarea/StudyAreaList.java
  src/main/java/task/Deadline.java
  src/main/java/task/Event.java
  src/main/java/task/TaskList.java
  src/main/java/ui/Constants.java
  src/main/java/ui/Ui.java
  src/test/java/task/event/TaskListTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/dukeLogger.log
  text-ui-test/input.txt
  text-ui-test/library/dictionary.txt
  text-ui-test/library/locations.txt
  text-ui-test/runtest.bat
Labels: type.Task

#73 Add Logging
  build.gradle
  dukeLogger.log
  library/taskList.txt
  src/main/java/command/AddDeadlineCommand.java
  src/main/java/command/AddEventCommand.java
  src/main/java/command/HelpCommand.java
  src/main/java/command/StudyAreaCommand.java
  src/main/java/exception/command/DeadlineCreationFormatNotFollowedException.java
  src/main/java/exception/command/EventCreationFormatNotFollowedException.java
  src/main/java/exception/command/EventStartTimeAfterEndTimeException.java
  src/main/java/exception/command/InvalidDateException.java
  src/main/java/exception/command/InvalidDueTimeException.java
  src/main/java/exception/command/InvalidEndTimeException.java
  src/main/java/exception/command/InvalidHelpCommandException.java
  src/main/java/exception/command/InvalidStartTimeException.java
  src/main/java/exception/command/SearchKeywordEmptyException.java
  src/main/java/exception/command/TaskDateBeforeCurrentDateException.java
  src/main/java/exception/command/TaskPriorityNotIntegerException.java
  src/main/java/resourceloader/TaskLoader.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/studyarea/StudyAreaList.java
  src/main/java/task/Deadline.java
  src/main/java/task/Event.java
  src/main/java/task/TaskList.java
  src/main/java/ui/Constants.java
  src/main/java/ui/Ui.java
  src/test/java/task/event/TaskListTest.java
  src/test/java/task/event/TaskTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/dukeLogger.log
  text-ui-test/input.txt
  text-ui-test/library/dictionary.txt
  text-ui-test/library/locations.txt
  text-ui-test/library/taskList.txt
  text-ui-test/runtest.bat
Labels: type.Task

#87 Rectify bug for issue #86
  dukeLogger.log
  src/main/java/resourceloader/BackUpData.java
  src/main/java/studyarea/StudyAreaList.java
  text-ui-test/EXPECTED.TXT
Labels: type.Bug

#88 Rectify bug
  dukeLogger.log
  src/main/java/exception/command/EmptyDescriptionException.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/task/Deadline.java
  src/main/java/task/Event.java
  src/main/java/ui/Constants.java
  src/main/java/ui/Ui.java
  src/test/java/task/EventTest.java
  src/test/java/task/TaskListTest.java
  text-ui-test/dukeLogger.log
Labels: severity.Low, type.Bug

#91 Add support for task scheduling
  dukeLogger.log
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/bookingsystem/BookingSystem.java
  src/main/java/bookingsystem/Test.java
  src/main/java/command/CreateScheduleCommand.java
  src/main/java/exception/command/MisuseOfClearCommandException.java
  src/main/java/exception/command/MisuseOfScheduleCommandException.java
  src/main/java/exception/command/NumberOfTasksToBeScheduledNotAnIntegerException.java
  src/main/java/exception/command/NumberOfTasksToBeScheduledNotPositiveException.java
  src/main/java/parser/Parser.java
  src/main/java/resourceloader/StudyAreaLoader.java
  src/main/java/resourceloader/TaskLoader.java
  src/main/java/task/SchedulableTask.java
  src/main/java/task/TaskComparator.java
  src/main/java/task/TaskScheduler.java
  src/main/java/ui/Constants.java
  src/test/java/parser/ParserTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/dukeLogger.log
  text-ui-test/library/dictionary.txt
  text-ui-test/library/locations.txt
  text-ui-test/library/taskList.txt
Labels: type.Story

#93 Add design details to Developer Guide
  docs/DeveloperGuide.md
  docs/images/Task_Component.jpg
  dukeLogger.log
  library/dictionary.txt
  library/locations.txt
  library/taskList.txt
  src/main/java/resourceloader/BackUpData.java
  src/main/java/task/Deadline.java
  src/main/java/task/Event.java
  src/main/java/ui/Constants.java
  src/test/java/task/TaskListTest.java
  src/test/java/task/TaskTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/dukeLogger.log
  text-ui-test/library/dictionary.txt
  text-ui-test/library/locations.txt
  text-ui-test/library/taskList.txt
Labels: type.Task

#96 Rectify mistake
  src/main/java/bookingsystem/Test.java
Labels: type.Task

#97 Rectify issue with JUnit Tests
  src/test/java/task/TaskListTest.java
  src/test/java/task/TaskTest.java
Labels: type.Task

#102 Add author tags
  src/main/java/command/AddDeadlineCommand.java
  src/main/java/command/AddEventCommand.java
  src/main/java/command/ClearCommand.java
  src/main/java/command/Command.java
  src/main/java/command/CountdownCommand.java
  src/main/java/command/CreateScheduleCommand.java
  src/main/java/command/DeleteCommand.java
  src/main/java/command/EditCommand.java
  src/main/java/command/HelpCommand.java
  src/main/java/command/PriorityViewCommand.java
  src/main/java/command/SearchCommand.java
  src/main/java/command/TaskCommand.java
  src/main/java/command/ViewCommand.java
  src/main/java/exception/command/DeadlineCreationFormatNotFollowedException.java
  src/main/java/exception/command/DeleteCommandMissingIndexException.java
  src/main/java/exception/command/EditCommandMissingIndexException.java
  src/main/java/exception/command/EmptyDescriptionException.java
  src/main/java/exception/command/EventCreationFormatNotFollowedException.java
  src/main/java/exception/command/EventDetailsNotProvidedException.java
  src/main/java/exception/command/EventStartTimeAfterEndTimeException.java
  src/main/java/exception/command/IndexNotIntegerException.java
  src/main/java/exception/command/InvalidDateException.java
  src/main/java/exception/command/InvalidDueTimeException.java
  src/main/java/exception/command/InvalidEndTimeException.java
  src/main/java/exception/command/InvalidHelpCommandException.java
  src/main/java/exception/command/InvalidStartTimeException.java
  src/main/java/exception/command/NumberOfTasksToBeScheduledNotAnIntegerException.java
  src/main/java/exception/command/NumberOfTasksToBeScheduledNotPositiveException.java
  src/main/java/exception/command/SearchKeywordEmptyException.java
  src/main/java/exception/command/SearchMissingTermsException.java
  src/main/java/exception/command/TaskDateBeforeCurrentDateException.java
  src/main/java/exception/command/TaskPriorityNotIntegerException.java
  src/main/java/parser/Parser.java
  src/main/java/resourceloader/TaskLoader.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/task/Event.java
  src/main/java/task/SchedulableTask.java
  src/main/java/task/Task.java
  src/main/java/task/TaskComparator.java
  src/main/java/task/TaskList.java
  src/main/java/task/TaskScheduler.java
  src/main/java/task/TaskType.java
  src/test/java/parser/ParserTest.java
  src/test/java/task/EventTest.java
  src/test/java/task/TaskListTest.java
  text-ui-test/dukeLogger.log
  text-ui-test/library/dictionary.txt
  text-ui-test/library/locations.txt
  text-ui-test/library/taskList.txt
Labels: type.Task

#103 Add author tags
  src/main/java/command/AddDeadlineCommand.java
  src/main/java/command/AddEventCommand.java
  src/main/java/command/ClearCommand.java
  src/main/java/command/Command.java
  src/main/java/command/CountdownCommand.java
  src/main/java/command/CreateScheduleCommand.java
  src/main/java/command/DeleteCommand.java
  src/main/java/command/EditCommand.java
  src/main/java/command/HelpCommand.java
  src/main/java/command/PriorityViewCommand.java
  src/main/java/command/SearchCommand.java
  src/main/java/command/TaskCommand.java
  src/main/java/command/ViewCommand.java
  src/main/java/exception/command/DeadlineCreationFormatNotFollowedException.java
  src/main/java/exception/command/DeleteCommandMissingIndexException.java
  src/main/java/exception/command/EditCommandMissingIndexException.java
  src/main/java/exception/command/EmptyDescriptionException.java
  src/main/java/exception/command/EventCreationFormatNotFollowedException.java
  src/main/java/exception/command/EventDetailsNotProvidedException.java
  src/main/java/exception/command/EventStartTimeAfterEndTimeException.java
  src/main/java/exception/command/IndexNotIntegerException.java
  src/main/java/exception/command/InvalidDateException.java
  src/main/java/exception/command/InvalidDueTimeException.java
  src/main/java/exception/command/InvalidEndTimeException.java
  src/main/java/exception/command/InvalidHelpCommandException.java
  src/main/java/exception/command/InvalidStartTimeException.java
  src/main/java/exception/command/NumberOfTasksToBeScheduledNotAnIntegerException.java
  src/main/java/exception/command/NumberOfTasksToBeScheduledNotPositiveException.java
  src/main/java/exception/command/SearchKeywordEmptyException.java
  src/main/java/exception/command/SearchMissingTermsException.java
  src/main/java/exception/command/TaskDateBeforeCurrentDateException.java
  src/main/java/exception/command/TaskPriorityNotIntegerException.java
  src/main/java/parser/Parser.java
  src/main/java/resourceloader/TaskLoader.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/task/Event.java
  src/main/java/task/SchedulableTask.java
  src/main/java/task/Task.java
  src/main/java/task/TaskComparator.java
  src/main/java/task/TaskList.java
  src/main/java/task/TaskScheduler.java
  src/main/java/task/TaskType.java
  src/test/java/parser/ParserTest.java
  src/test/java/task/EventTest.java
  src/test/java/task/TaskListTest.java
  text-ui-test/dukeLogger.log
  text-ui-test/library/dictionary.txt
  text-ui-test/library/locations.txt
  text-ui-test/library/taskList.txt
Labels: type.Task

#108 Add authorship for DG
  docs/DeveloperGuide.md
Labels: type.Task

#118 Add authorship for DG
  docs/DeveloperGuide.md
  docs/images/StudyAreaObjectDiagram.png
Labels: type.Task

#117 Add Redo and undo function
  src/main/java/notes/Example.java
  src/main/java/notes/ModulesList.java
  src/main/java/notes/Notes.java
  src/main/java/notes/modules/Add.java
  src/main/java/notes/modules/Module.java
  src/main/java/notes/modules/ModuleManager.java
  src/main/java/notes/modules/Remove.java
  src/main/java/notes/modules/Update.java
  src/main/java/notes/modules/command/AddCommand.java
  src/main/java/notes/modules/command/Command.java
  src/main/java/notes/modules/command/CommandStack.java
  src/main/java/notes/modules/command/ExitCommand.java
  src/main/java/notes/modules/command/ListCommand.java
  src/main/java/notes/modules/parser/Parser.java
  src/main/java/notes/modules/tracking/History.java
  src/main/java/notes/modules/tracking/Redo.java
  src/main/java/notes/modules/tracking/Undo.java
Labels: type.Epic, type.Story, type.Task

#120 Update UG and add minor changes to code
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/notes/ModulesList.java
  src/main/java/notes/Notes.java
  src/main/java/notes/modules/parser/Parser.java
  src/main/java/task/Deadline.java
  src/main/java/task/TaskList.java
  src/main/java/ui/Constants.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/dukeLogger.log
Labels: type.Task

#121 Rectify issues with UG
  docs/UserGuide.md
Labels: type.Task

#122 Rectify formatting issues with UG
  docs/UserGuide.md
Labels: type.Task

#124 implement isDone for deadline
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/bookingsystem/BookingSystem.java
  src/main/java/bookingsystem/Test.java
  src/main/java/command/AddDeadlineCommand.java
  src/main/java/command/CommandWithIndex.java
  src/main/java/command/DeleteCommand.java
  src/main/java/command/DoneCommand.java
  src/main/java/command/EditCommand.java
  src/main/java/command/TaskCommand.java
  src/main/java/command/studyarea/StudyAreaCommand.java
  src/main/java/exception/IllegalStudyAreaException.java
  src/main/java/exception/command/DeleteCommandMissingIndexException.java
  src/main/java/exception/command/EditCommandMissingIndexException.java
  src/main/java/exception/command/IllegalDoneCommandException.java
  src/main/java/exception/command/IndexNotIntegerException.java
  src/main/java/exception/command/MissingIndexException.java
  src/main/java/exception/command/MisuseOfSetDoneWithEvent.java
  src/main/java/parser/Parser.java
  src/main/java/resourceloader/TaskLoader.java
  src/main/java/studyarea/StudyArea.java
  src/main/java/task/Deadline.java
  src/main/java/task/Event.java
  src/main/java/task/TaskList.java
  src/main/java/ui/Constants.java
  src/test/java/parser/ParserTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/dukeLogger.log
  text-ui-test/input.txt
  text-ui-test/library/dictionary.txt
  text-ui-test/library/locations.txt
  text-ui-test/library/taskList.txt
Labels: type.Task

#127 Add notes into main and update expected.txt
  text-ui-test/EXPECTED.TXT
  text-ui-test/dukeLogger.log
  text-ui-test/library/dictionary.txt
  text-ui-test/library/locations.txt
  text-ui-test/library/taskList.txt
Labels: type.Task

#125 Update code to support isDone field of Deadline class
  docs/UserGuide.md
  dukeLogger.log
  library/dictionary.txt
  library/locations.txt
  library/taskList.txt
  src/main/java/exception/command/DeadlineCompletionStatusNotABooleanException.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/task/Deadline.java
  src/main/java/ui/Constants.java
  src/main/java/ui/Ui.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/dukeLogger.log
  text-ui-test/input.txt
  text-ui-test/library/dictionary.txt
  text-ui-test/library/locations.txt
  text-ui-test/library/taskList.txt
Labels: type.Task

#128 Update UG
  docs/UserGuide.md
Labels: type.Task

#129 Rectify minor formatting issue
  docs/UserGuide.md
Labels: type.Task

#130 Update DG and restructure code
  docs/DeveloperGuide.md
  docs/UML tP.pptx
  docs/images/Schedule_Overall.png
  docs/images/Schedule_Sub1.png
  docs/images/Schedule_Sub2.png
  docs/images/Schedule_Sub3.png
  docs/images/StudyAreaObjectDiagram.png
  docs/images/studyAreaSequenceDiagram.png
  src/main/java/command/TaskCommand.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/task/SchedulableTask.java
  src/main/java/task/TaskScheduler.java
Labels: type.Task

#131 Add UML Code and Architecture diagram to DG
  .gitignore
  docs/DeveloperGuide.md
  docs/UML Code/AddScheduledTasksToList.txt
  docs/UML Code/Architecture.txt
  docs/UML Code/CheckAndScheduleTasks.txt
  docs/UML Code/GetSchedulabeTaskInformation.txt
  docs/UML Code/TaskComponent.txt
  docs/UserGuide.md
  docs/images/Architecture.png
  docs/images/Task_Component_UML.png
Labels: type.Task

#132 Change directory name of UML Code to UML_Code
  docs/UML_Code/AddScheduledTasksToList.txt
  docs/UML_Code/Architecture.txt
  docs/UML_Code/CheckAndScheduleTasks.txt
  docs/UML_Code/GetSchedulabeTaskInformation.txt
  docs/UML_Code/TaskComponent.txt
Labels: type.Task

#135 update DG
  docs/DeveloperGuide.md
  docs/images/Schedule_Overall.png
  docs/images/Schedule_Sub1.png
  docs/images/isAvailStudyArea.png
  docs/images/sL_sA_interaction.png
  docs/images/user_sL_interaction.png
Labels: type.Task

#136 Update DG
  docs/DeveloperGuide.md
  docs/UML_Code/AddScheduledTasksToList.txt
  docs/UML_Code/CheckAndScheduleTasks.txt
  docs/UML_Code/GetSchedulabeTaskInformation.txt
  docs/UML_Code/Schedule_Overall.txt
  docs/images/Schedule_Overall.png
  docs/images/Schedule_Sub1.png
  docs/images/Schedule_Sub2.png
  docs/images/Schedule_Sub3.png
Labels: type.Task

#137 Finalize notes
  src/main/java/notes/ModulesList.java
  src/main/java/notes/Notes.java
  src/main/java/notes/NotesInvoker.java
  src/main/java/notes/modules/ModuleManager.java
  src/main/java/ui/Constants.java
Labels: type.Epic, type.Story, type.Task
